# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@master
    # Build & deploy
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        # Target branch
        PAGES_BRANCH: gh-pages
        BUILD_DIR: Blog
        BUILD_FLAGS: --drafts
        # Provide personal access token
        TOKEN: ${{ secrets.TOKEN }}
